In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("customer_shopping_behavior.csv")
df.head()

df.info

<bound method DataFrame.info of       Customer ID  Age  Gender Item Purchased     Category  \
0               1   55    Male         Blouse     Clothing
1               2   19    Male        Sweater     Clothing
2               3   50    Male          Jeans     Clothing
3               4   21    Male        Sandals     Footwear
4               5   45    Male         Blouse     Clothing
...           ...  ...     ...            ...          ...
3895         3896   40  Female         Hoodie     Clothing
3896         3897   52  Female       Backpack  Accessories
3897         3898   46  Female           Belt  Accessories
3898         3899   44  Female          Shoes     Footwear
3899         3900   52  Female        Handbag  Accessories

      Purchase Amount (USD)       Location Size      Color  Season  \
0                        53       Kentucky    L       Gray  Winter
1                        64          Maine    L     Maroon  Winter
2                        73  Massachusetts    S     Maroon  Spring
3                        90   Rhode Island    M     Maroon  Spring
4                        49         Oregon    M  Turquoise  Spring
...                     ...            ...  ...        ...     ...
3895                     28       Virginia    L  Turquoise  Summer
3896                     49           Iowa    L      White  Spring
3897                     33     New Jersey    L      Green  Spring
3898                     77      Minnesota    S      Brown  Summer
3899                     81     California    M      Beige  Spring

      Review Rating Subscription Status   Shipping Type Discount Applied  \
0               3.1                 Yes         Express              Yes
1               3.1                 Yes         Express              Yes
2               3.1                 Yes   Free Shipping              Yes
3               3.5                 Yes    Next Day Air              Yes
4               2.7                 Yes   Free Shipping              Yes
...             ...                 ...             ...              ...
3895            4.2                  No  2-Day Shipping               No
3896            4.5                  No    Store Pickup               No
3897            2.9                  No        Standard               No
3898            3.8                  No         Express               No
3899            3.1                  No    Store Pickup               No

     Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
0                Yes                  14          Venmo            Fortnightly
1                Yes                   2           Cash            Fortnightly
2                Yes                  23    Credit Card                 Weekly
3                Yes                  49         PayPal                 Weekly
4                Yes                  31         PayPal               Annually
...              ...                 ...            ...                    ...
3895              No                  32          Venmo                 Weekly
3896              No                  41  Bank Transfer              Bi-Weekly
3897              No                  24          Venmo              Quarterly
3898              No                  24          Venmo                 Weekly
3899              No                  33          Venmo              Quarterly

[3900 rows x 18 columns]>

In [6]:
df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [ ]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [61]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [62]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [64]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [65]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [66]:
#create a column age_group
labels = ['Young Adult','Adult','Middle-aged','Senior']
df['age_group'] = pd.qcut(df['age'],q =4, labels = labels)

In [67]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [68]:
# create column purchase_frequency_days
frequency_mapping = {
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [69]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [25]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [70]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [71]:
df =df.drop('promo_code_used',axis = 1)

In [72]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [38]:
!pip install mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector-python in C:\Users\vivek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (9.4.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: C:\Users\vivek\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [73]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Vivek",
    database="customer_bahavior"
)

cursor = conn.cursor()
print("Connected successfully!")

Connected successfully!

In [74]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+mysqlconnector://root:Vivek@localhost/customer_bahavior"
)

print("MySQL connected successfully!")

MySQL connected successfully!

In [75]:
df.to_sql(
    name="customer_data",
    con=engine,
    if_exists="replace",
    index=False
)

print("DataFrame loaded into MySQL successfully!")

DataFrame loaded into MySQL successfully!

In [76]:

df.to_sql(
    name="customer_data",
    con=engine,
    if_exists="replace",
    index=False
)

print("DataFrame loaded into MySQL successfully!")
data = pd.read_sql(
    "SELECT * FROM customer_data",
    engine
)

display(data.head())

DataFrame loaded into MySQL successfully!

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365

In [ ]:
select age_group,
sum(purchase_amount) as total_revenue
from customer_data
group by age_group
order by total_revenue;